language: python
python:
  - "3.7"

addons:
  postgresql: "9.6"

install:
  - pip install coveralls
  - pip install black
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py migrate

script:
  - black . --exclude venv -l 79 --check
  - pytest

after_success:
  - coveralls
