# Generated by Django 2.2.3 on 2019-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0003_content_file_image_text_video")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="image",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="text",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="video",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
