# Generated by Django 2.2.3 on 2019-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0007_course_image")]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files"),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.FileField(upload_to="videos"),
        ),
    ]
