# Generated by Django 2.2.3 on 2019-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0010_auto_20190726_0754")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(default="default.jpg", upload_to="images"),
        ),
    ]
